### ISSUE TITLE
Preserve work directory for failed tests irrespective of `angela.skipUninstall` property value

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/angela#11]
Just the OSS system tests of our project accounts for more than 8GB of data.... This is huge considering the limitations of our jenkins nodes.

![image](https://user-images.githubusercontent.com/61346/74765115-f8028f00-5250-11ea-93ef-81b064955fa8.png)

**Comment by mathieucarbou** [comment]
Note: what we used to do is only keep the data if the test is in error (and just the meaningfull data, not the whole kit)

**Comment by aurbroszniowski** [comment]
This is probably the angela.skipUninstall system property which is set in the tests

**Comment by mathieucarbou** [comment]
If I remove it, will it only clean the data of successful tests, or all test tests ?

> This is probably the angela.skipUninstall system property which is set in the tests

**Comment by aurbroszniowski** [comment]
it will clean all tests
 if you need a mechanism to avoid cleaning failed tests, let me know, this shouldn't be hard to add

**Comment by mathieucarbou** [comment]
Yes, we need.... We have that in Glavan and we had that in dynamic config with out test infra too. This is useful since most of our relevant data is in the server logs, not in system out.

Thanks :-)

> oid cleaning failed tests, let me know, this shouldn't be hard t

**Comment by saurabhagas** [comment]
Preserve only the test data once a test has failed, instead of preserving the entire `work` directory for the test. This would help save space on PR builds, where multiple tests fail.

**Comment by saurabhagas** [comment]
Obsolete with the introduction of AngelaRule, and avoiding kit copying
