### ISSUE TITLE
Angela is copying the KIT for each test

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/angela#12]
With the infra we had before, we didn't need to copy the KIT. 

The KIT files were copied by gradle and then we were created one working directory per test using these KIT files.

The only file that could be moved to the KIT was the `logback-ext.xml` file for the logging. But this file is places in the test/resources folder and then could be considered common to all tests and we then could create a KIT one time with this file and reuse the same KIT files for all the tests, as long as the working directories are not the same.

This would help improve the work dir size and test speed (#10 and #11)

**Comment by aurbroszniowski** [comment]
The reason why it copies the kit is for test isolation, the copy itself is supposed to be negligible. 
A review of the current logic is needed, there might have been an issue introduced during the refactoring of pulling common install code in a new KitUtils class

**Comment by saurabhagas** [comment]
I think the problem here is not of speed, but of space. The duplicate kits can occupy a lot of unnecessary space on failed tests in PRs. What we could do is preserve only the test data once a test has failed, instead of preserving the entire `work` directory for the test.

**Comment by saurabhagas** [comment]
Completed.

**Comment by mathieucarbou** [comment]
@aurbroszniowski : we should adapt Angela tp be able to get what was possible with Galvan. Galvan was copying the kit before and it was creating space issues in jenkins nodes, regardless whether tests were failing or not.
