### ISSUE TITLE
We should be able to remove any JDK constraint easily

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/angela#14]
Setting `angela.java.vendor` to `''` or `null` is not working and takes the default to Zulu.

We should be able to tell Angela to not apply any constraint on the JDK vendor name and/or version

The issue is this code in `AngelaProperties`:

```
public String getValue() {
  String specifiedValue = getSpecifiedValue();
  return specifiedValue == null || specifiedValue.isEmpty() ? getDefaultValue() : specifiedValue;
}
```

Applying the default shouldn't  be the responsibility of this class, but instead the caller. This class should instead return an optional and let the caller decide what to do, and eventually apply a different behavior depending whether the prop is there or not (like removing constraint on JDK version and/or vendor)

```
public Optiona<String> getValue() {
  String specifiedValue = getSpecifiedValue();
  return specifiedValue == null || specifiedValue.isEmpty() ? Optional.empty() : Optional.of(specifiedValue);
}
```

**Comment by saurabhagas** [comment]
We could allow any Java vendor by default. So not specifying  `angela.java.vendor` would result in any Java Vendor being acceptable, as long as there's at least one vendor found in `toolchains.xml`

**Comment by mathieucarbou** [comment]
why relying on toolchain ? If I am ok to use any vendor, as long as a JRE is available on the system, which is since Angela was started, then this is fine. 
I would get rid of this requirement to have a toolchain , except if we specify a specific vendor or version, and in this case, yes, we need to look into the toolchain for the right path to use.

**Comment by saurabhagas** [comment]
Done via PR#18.
