### ISSUE TITLE
Angela should provide a Junit rule, like Galvan

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/angela#31]
To be able to correctly fix these issues:

- [ ] https://github.com/Terracotta-OSS/angela/issues/29
- [ ] https://github.com/Terracotta-OSS/angela/issues/11

CC @chrisdennis @myronkscott @cljohnso @akomakom

**Comment by mathieucarbou** [comment]
Implementing a fix in https://github.com/Terracotta-OSS/terracotta-platform/pull/678 and will soon extract a AngelaRule from what we have in tc-platform (work already done at 80%).

**Comment by mathieucarbou** [comment]
resolved

**Comment by saurabhagas** [comment]
Fixed with the introduction of AngelaRule
