### ISSUE TITLE
Add custom TSA logging

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/angela#52]
TSA uses custom logging to take jfr recordings if available.  Install a logback-test.xml file in the working directory of 107 distribution of TSA

**Comment by aurbroszniowski** [comment]
I believe that the logback config is supposed to be installed in the test project, since Angela is using slf4j to log and it is the responsability of the test to define its specific logging configuration

**Comment by myronkscott** [comment]
Right.  That is for the test itself.  The server needs a different logback configuration installed in the working directory

**Comment by aurbroszniowski** [comment]
if you need to upload a specific file to a Terracotta server you can use the 'browse()' method

here it uploads the logback file to the 'server' directory of the first terracotta server (index =0) for the second stripe (index =1)
```
      tsa.browse(tsa.getServer(1,0), "server").upload(new File("logback-test.xml"));
```

**Comment by myronkscott** [comment]
I'd prefer to make it part of the standard distribution so we don't have to upload it for every test primitive but I suppose that would work as well.

**Comment by aurbroszniowski** [comment]
isn't there a way to incude this mechanism in the Base Test class of the project you're using? (I saw that all tests in teracotta-ee are always inheriting some base test class which creates the Tsa)

**Comment by myronkscott** [comment]
There is a different base class in platform.  Plus there is plan to have wider usage of angela across the stack.  I'm trying to figure out how to make usage of the example above but not having much success.  I can possibly add it to AngelaRule but I'm not sure everyone will use that.

**Comment by aurbroszniowski** [comment]
as discussed, let's review this next week and decide of the implementation

**Comment by myronkscott** [comment]
Implemented as suggested
